[tool.poetry]
name = "spotifymatcher"
version = "0.1.0"
description = ""
authors = ["Bosco Domingo <boscodomingob@gmail.com>"]
license = "GNU"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
spotipy = "^2.23.0"
eyed3="^0.9.6"
tinytag="^1.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
