[tool.poetry]
authors = ["Bosco Domingo <boscodomingob@gmail.com>"]
description = ""
license = "GNU"
name = "SpotifyMatcher"
readme = "README.md"
version = "2.0.0"
packages = [{include = "main.py"}]

[tool.poetry.dependencies]
python = "^3.10"
eyed3 = "^0.9.6"
spotipy = "^2.23.0"
tinytag = "^1.7.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
